FROM node:20-alpine AS builder
WORKDIR /app
COPY ui/package*.json ./
RUN npm install
COPY ui/ .
ARG VITE_COURSE_MGMT_URL=http://localhost:3004
ENV VITE_COURSE_MGMT_URL=$VITE_COURSE_MGMT_URL
RUN npm run build

FROM nginx:alpine AS runner
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 3014
CMD ["nginx", "-g", "daemon off;"]
