server {
    listen 3011;
    listen [::]:3011;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, OPTIONS";
        add_header Access-Control-Allow-Headers "*";
    }

    location ~* \.(js|css|woff|woff2|ttf|eot|svg)$ {
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location /nginx-health {
        return 200 "ok";
        add_header Content-Type text/plain;
    }
}
